volumes:
  postgres-data:
  redis-data:

services:
  postgres:
    image: "docker.io/postgres:15-alpine"
    restart: "always"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  redis:
    image: "docker.io/redis:7-alpine"
    restart: "always"
    volumes:
      - "redis-data:/data"
    ports:
      - "6379:6379"
