#!/usr/bin/bash
set -e
set -o noclobber
set -o pipefail

# full upgrade
sudo pacman -Syu
yay -Syu

# remove orphaned packages
sudo pacman -Qtdq | sudo pacman -Rns - || true
yay -Qtdq | yay -Rns - || true

# clean the package cache
yay -Sc

# reboot the system
declare should_reboot
read -N 1 -p "Arch update is finished! Would you like to reboot? (y/n) " should_reboot

if [[ "${should_reboot}" == "y" ]]; then
	systemctl reboot
fi
