#!/usr/bin/env bash
set -e
set -o noclobber
set -o pipefail

readonly PROFILE_DIR="$(echo "${HOME}"/.mozilla/firefox/*.default-release)"

if [[ ! -d "${PROFILE_DIR}" ]]; then
  exit 1
fi

#####################################
# Download arkenfox files if needed #
#####################################
readonly BASE_URL="https://raw.githubusercontent.com/arkenfox/user.js/master"
readonly -a FILE_NAMES=(
  "prefsCleaner.sh"
  "updater.sh"
  "user.js"
)
declare full_path

for file_name in "${FILE_NAMES[@]}"; do
  file_path="${PROFILE_DIR}/${file_name}"
  
  # If the file doesn't exist, then download it
  if [[ ! -f "${file_path}" ]]; then
    curl "${BASE_URL}/${file_name}" > "${file_path}"
    chmod +x "${file_path}"
  fi
done

######################
# Perform the update #
######################
"${PROFILE_DIR}"/updater.sh -o "${XDG_CONFIG_HOME}/arkenfox/user-overrides.js"
"${PROFILE_DIR}"/prefsCleaner.sh -s
