#!/usr/bin/env bash
set -e
set -o noclobber
set -o pipefail

# An extremely incomplete script at the moment...

# Todo: Install brew first?
# Todo: Make a Brewfile?
brew install romkatv/powerlevel10k/powerlevel10k
brew install zoxide
