#!/usr/bin/env bash
set -e
set -o noclobber
set -o pipefail

# install stuff
case "${OSTYPE}" in
	"darwin"*)
		brew install gnupg pass spotifyd spotify-tui
		;;
	"linux"*)
		[[ "$(cat /etc/os-release)" =~ "ID=arch" ]] && \
			yay -S gnupg pass rust spotifyd spotify-tui
		;;
esac

# generate gpg key
gpgconf --kill gpg-agent
gpg --full-gen-key

# get the key id
declare -r public_keys="$( gpg --list-keys --with-colons | grep "pub" )"
declare -ir num_keys="$( wc -l <<< "${public_keys}" )"

if (( "${num_keys}" != 1 )); then
	echo "Found more than one gpg key! Aborting..."
	exit 1
fi

declare -r key_id="$( cut --delimiter=":" --fields=5 <<< "${public_keys}" )"

# initialize pass
pass init "${key_id}"

declare username password
read -p "Spotify username: " username
read -s -p "Spotify password: " password
echo ""

pass insert --echo spotify/username <<< "${username}"
pass insert --echo spotify/password <<< "${password}"
