import = [
  "~/.config/alacritty/colorschemes/catppuccin-mocha.toml",
]

[font]
size = 15
# normal.family = "Hack Nerd Font"
# size = 19
# normal.family = "UbuntuMono Nerd Font"

# normal.family = "JetBrainsMono Nerd Font"

# normal.family = "CodeNewRoman Nerd Font"
# normal.family = "CommitMono Nerd Font"
# normal.family = "OverpassM Nerd Font"

# normal.family = "BlexMono Nerd Font"
# normal.family = "BlexMono Nerd Font Propo"

normal.family = "DejaVuSansM Nerd Font"
# normal.family = "iMWritingMono Nerd Font"

[cursor]
blink_interval = 500
style.shape = "Block"
style.blinking = "Always"

[window]
decorations = "none"
startup_mode = "Maximized"
padding = { x = 5, y = 5 }
